# Site settings
title: Matt's Projects
description: This is the portfolio of Matt Clinard
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
baseurl: ""
url: "https://cclinard84.github.io"
# User settings
username: Matt Clinard
user_description:
user_title: Husband/Father to Be/Software Developer
email: cclinard84@gmail.com
twitter_username: CMattClinard
github_username:  cclinard84

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
